version: 2.1
jobs:
  build:
    working_directory: ~/jira-templator
    docker:
      - image: circleci/node:16-browsers
    steps:
      - checkout:
          path: ~/jira-templator
      - run:
          working_directory: ~/jira-templator/jit
          name: Install Packages
          command: npm install
      - run:
          working_directory: ~/jira-templator/jit
          name: Linting
          command: npm run lint
      - run:
          working_directory: ~/jira-templator/jit
          name: Building
          command: npm run build-normal
      - persist_to_workspace:
          root: .
          paths:
            - .
  test:
    working_directory: ~/jira-templator
    docker:
      - image: circleci/node:16-browsers
    steps:
      - attach_workspace:
          at: ~/jira-templator
      - run:
          working_directory: ~/jira-templator/jit
          name: Run Tests
          command: npm run test-ci
  pack:
    working_directory: ~/jira-templator
    docker:
      - image: circleci/node:16-browsers
    steps:
      - attach_workspace:
          at: ~/jira-templator
      - run:
          working_directory: ~/jira-templator/jit
          name: Build Cleanup
          command: npm run pack-clean
      - run:
          working_directory: ~/jira-templator/jit
          name: Build Pack
          command: npm run pack-it
      - run:
          working_directory: ~/jira-templator/jit
          name: Show me what we have there
          command: |
            ls -la .
            echo '----------------------------------'
            echo '----------------------------------'
            echo '----------------------------------'
            ls -la ../
  release:
    working_directory: ~/jira-templator
    docker:
      - image: circleci/node:16-browsers
    environment:
      SOURCE_BRANCH: test-main
      RELEASE_BRANCH: test-release
      INCREMENT_TYPE: minor
    steps:
      - checkout:
          path: ~/jira-templator
      # - run:
      #     working_directory: ~/jira-templator/jit
      #     name: Install packages
      #     command: npm install
      # - run:
      #     working_directory: ~/jira-templator/jit
      #     name: Build project
      #     command: npm run build-normal
      # - run:
      #     working_directory: ~/jira-templator/jit
      #     name: Merge latest develop into release branch
      #     command: |
      #       ls -la .
      #       echo '----------------------------------'
      #       ls -la ../
      - run:
          working_directory: ~/jira-templator/jit
          name: Merge latest develop into release branch
          command: |
            git checkout test-release
            git pull origin develop -s ours
            git checkout test-release
            git merge develop
      # - run:
      #     working_directory: ~/jira-templator/jit
      #     name: Increment version value
      #     command: |
      #       git checkout test-release
      #       git pull origin develop -s ours
      #       git checkout test-release
      #       git merge develop

workflows:
  version: 2.1
  # jt:
  #   jobs:
  #     - build
  #     - test:
  #         requires:
  #           - build
  #     - pack:
  #         requires:
  #           - test
  jt-release:
    jobs:
      - release-approval:
          type: approval
          # filters:
          #     branches:
          #         only:
          #             - main
      - release:
          requires:
              - release-approval
    
    

