version: 2.1
jobs:
  build:
    working_directory: ~/jira-templator
    docker:
      - image: circleci/node:16-browsers
    steps:
      - checkout:
          path: ~/jira-templator
      - run:
          working_directory: ~/jira-templator/jit
          name: Install Packages
          command: npm install
      - run:
          working_directory: ~/jira-templator/jit
          name: Linting
          command: npm run lint
      - run:
          working_directory: ~/jira-templator/jit
          name: Building
          command: npm run build-normal
      - persist_to_workspace:
          root: .
          paths:
            - .
  test:
    working_directory: ~/jira-templator
    docker:
      - image: circleci/node:16-browsers
    steps:
      - attach_workspace:
          at: ~/jira-templator
      - run:
          working_directory: ~/jira-templator/jit
          name: Run Tests
          command: npm run test-ci
  pack:
    working_directory: ~/jira-templator
    docker:
      - image: circleci/node:16-browsers
    steps:
      - attach_workspace:
          at: ~/jira-templator
      - run:
          working_directory: ~/jira-templator/jit
          name: Build Cleanup
          command: npm run pack-clean
      - run:
          working_directory: ~/jira-templator/jit
          name: Build Pack
          command: npm run pack-it
      - run:
          working_directory: ~/jira-templator/jit
          name: Show me what we have there
          command: |
            ls -la .
            echo '----------------------------------'
            echo '----------------------------------'
            echo '----------------------------------'
            ls -la ../
  release:
    working_directory: ~/jira-templator
    docker:
      - image: circleci/node:16-browsers
    environment:
      SOURCE_BRANCH: test-main
      RELEASE_BRANCH: test-release
      INCREMENT_TYPE: minor
    steps:
      - checkout:
          path: ~/jira-templator
      # - run:
      #     working_directory: ~/jira-templator/jit
      #     name: Install packages
      #     command: npm install
      # - run:
      #     working_directory: ~/jira-templator/jit
      #     name: Build project
      #     command: npm run build-normal
      # - run:
      #     working_directory: ~/jira-templator/jit
      #     name: Merge latest develop into release branch
      #     command: |
      #       ls -la .
      #       echo '----------------------------------'
      #       ls -la ../
      - run:
          working_directory: ~/jira-templator/jit
          name: Configure Git
          command: |
            git config --global user.email $GIT_EMAIL
            git config --global user.name $GIT_USER_NAME
      - run:
          working_directory: ~/jira-templator/jit
          name: Merge latest develop into release branch
          command: npm run merge:ci
      - run:
          name: Check out release branch
          command: git checkout $RELEASE_BRANCH
      - run:
          working_directory: ~/jira-templator/jit
          name: Set Release Version
          command: npm --no-git-tag-version version $INCREMENT_TYPE
      - run:
          name: Commit and Push Release Branch Changes
          command: |
              git commit -am "update files for new version"
              git push --verbose
      # - run:
      #     name: Increment source branch version
      #     command: |
      #         git checkout $SOURCE_BRANCH
      #         npm --no-git-tag-version version $INCREMENT_TYPE
      # - run:
      #     name: Push source branch changes
      #     command: |
      #         git commit -am 'increment develop versions'
      #         git push origin $SOURCE_BRANCH
      - run:
          name: Get the branch
          command: git checkout feature/adding-release-script
      - run:
          working_directory: ~/jira-templator/jit
          name: Trigger release branch
          command: npm run trigger-pipeline:ci ${RELEASE_BRANCH}

workflows:
  version: 2.1
  # jt:
  #   jobs:
  #     - build
  #     - test:
  #         requires:
  #           - build
  #     - pack:
  #         requires:
  #           - test
  jt-release:
    jobs:
      - release-approval:
          type: approval
          # filters:
          #     branches:
          #         only:
          #             - main
      - release:
          requires:
              - release-approval
    
    

