version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:16-browsers
    steps:
      - checkout:
          path: ~/jira-templator
      - run:
          working_directory: ~/jira-templator/jit
          name: Install Packages
          command: npm install
      - run:
          working_directory: ~/jira-templator/jit
          name: Linting
          command: npm run lint
      - run:
          working_directory: ~/jira-templator/jit
          name: Building
          command: npm run build-normal
      - persist_to_workspace:
          root: ./jira-templator
          paths:
              - jit
              - .git
              - package.json
  test:
    working_directory: ~/jira-templator
    docker:
      - image: circleci/node:16-browsers
    steps:
      - run:
          working_directory: ~/jira-templator/jit
          name: Run Tests
          command: npm run test-ci
  pack:
    working_directory: ~/jira-templator
    docker:
      - image: circleci/node:16-browsers
    steps:
      - run:
          working_directory: ~/jira-templator/jit
          name: Build Cleanup
          command: npm run pack-clean
      - run:
          working_directory: ~/jira-templator/jit
          name: Build Pack
          command: npm run pack-it
      - run:
          working_directory: ~/jira-templator/jit
          name: Show me what we have there
          command: |
            ls -la .
            echo '----------------------------------'
            echo '----------------------------------'
            echo '----------------------------------'
            ls -la ./dist

workflows:
  version: 2.1
  jt:
    jobs:
      - build
      - test:
          requires:
            - build
      - pack:
          requires:
            - test
    
    

